### ISSUE TITLE
Question on Rationale Format

### ISSUE THREAD

**Issue by ajyl** [behavioral-data/Empathy-Mental-Health#11]
Hi @ash-shar ,

I've enjoyed your paper. I had a quick question on how you are processing your training data. Specifically, [here](https://github.com/behavioral-data/Empathy-Mental-Health/blob/master/src/process_data.py#L63-L65), if I understand correctly, this is the case in which there are no rationales. However, why are you masking the response as 1's?

Some insight into this would be very helpful. Thank you!

Best,
Andrew

**Comment by ash-shar** [comment]
Hi @ajyl,

Sorry for the slow reply. Haven't been following this repository of late.

To answer your question, the idea is that if no rationales have been identified for a response, then we consider the entire response as a rationale (because no specific portions of the response led to someone labeling the response as 0, 1 or 2;  the entire response was a "rationale" for its labeling instead). Ultimately, it is a heuristic we have used to handle the case of missing rationales and it might be interesting to evaluate other heuristics. Hope this clarifies your doubt and let me know if it is unclear.

Thanks!
